Update docker-image.yml
Signed-off-by: AndyWanng <95070150+AndyWanng@users.noreply.github.com>

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -27,12 +27,21 @@ jobs:
       run: |
         cd src/Components
         docker-compose up
-        
+    
+    - name: Wait for containers to be ready
+      run: sleep 180
+      
     - name: Check running containers
       run: |
         cd src/Components
-        docker-compose ps
-        
+        RUNNING_CONTAINERS=$(docker-compose ps | grep 'Up' | wc -l)
+        if [ "$RUNNING_CONTAINERS" -eq 9 ]; then
+          echo "All containers are up and running."
+        else
+          echo "Expected 9 running containers, but found $RUNNING_CONTAINERS. Failing."
+          exit 1
+        fi
+  
     - name: Stop and remove containers
       run: |
         cd src/Components
